const swaggerJsdoc = require('swagger-jsdoc');

const options = {
    // List of files to be processes. You can also set globs './routes/*.js'
    apis: ['./routes/*.js'],
    basePath: '/',
    swaggerDefinition: {
      // Like the one described here: https://swagger.io/specification/#infoObject
      info: {
        description: 'Test API with autogenerated swagger doc',
        swagger: '2.0',
        title: 'News API',
        version: '1.0.0',
      },
      securityDefinitions: {
        Basic: {
          type: 'apiKey',
          in: 'header',
          name: 'Authorization',
        },
      },
      security: {
        Basic: [],
      },
    },
};

const specs = swaggerJsdoc(options);
export default specs;