version: "3"
services:
  redis:
    container_name: news-redis1
    image: redis
    ports:
      - "6379:6379"
  mongodb:
    image: tutum/mongodb
    ports:
      - "27017:27017"
      - "28017:28017"
    environment:
      - AUTH=no